# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import complex_service_pb2 as complex__service__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in complex_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComplexServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComplexMethod = channel.unary_unary(
                '/complex_service.ComplexService/ComplexMethod',
                request_serializer=complex__service__pb2.DeviceData.SerializeToString,
                response_deserializer=complex__service__pb2.DeviceData.FromString,
                _registered_method=True)


class ComplexServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComplexMethod(self, request, context):
        """Defines the CheckBandwidth method that the server implements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComplexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComplexMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.ComplexMethod,
                    request_deserializer=complex__service__pb2.DeviceData.FromString,
                    response_serializer=complex__service__pb2.DeviceData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'complex_service.ComplexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('complex_service.ComplexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComplexService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComplexMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/complex_service.ComplexService/ComplexMethod',
            complex__service__pb2.DeviceData.SerializeToString,
            complex__service__pb2.DeviceData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
